DEFAULT_PARAMS_SET: Chen2020
EXP_INDEX: 1
EXP_SETTING:
  charge_c_rate: 0.2
  discharge_c_rate: 0.2
  exp_index: 1
  model_name: DFN
  param_name: Chen2020
  parameter_change:
    Negative particle radius [m]: 1.172e-05
MODEL_NAME: DFN
MODEL_OPTIONS:
  SEI: reaction limited
  SEI film resistance: distributed
SETTING_FILE: ./generate_simulated_data/output/simulated_data_setting_single_new_filtered.yaml
SINGLE_CYCLE:
- Rest for 120 seconds
- Charge at 0.2C until 4.2 V
- Rest for 120 seconds
- Hold at 4.2 V until 50 mA
- Rest for 90 seconds
- Discharge at 0.2C until 2.7 V
- Rest for 90 seconds
