DEFAULT_PARAMS_SET: Ai2020
EXP_INDEX: 233
EXP_SETTING:
  charge_c_rate: 2
  discharge_c_rate: 2
  exp_index: 233
  model_name: DFN
  param_name: Ai2020
  parameter_change:
    Positive electrode thickness [m]: 0.00015000000000000001
MODEL_NAME: DFN
MODEL_OPTIONS:
  SEI: reaction limited
  SEI film resistance: distributed
SETTING_FILE: ../../generate_simulated_data/output/simulated_data_setting_single_new_filtered.yaml
SINGLE_CYCLE:
- Rest for 1 second
- Charge at C/2 until 4.2 V
- Rest for 1 second
- Hold at 4.2 V until C/20
- Rest for 90 second
- Discharge at C/2 until 2.7 V
- Rest for 90 second
