EXPERIMENT_TYPE: sim_vs_sim
EXP_CYCLES: 200
RANDOM_SEED: 1234
REAL_VS_SIM:
  real_world_cell_dataset: MATR
  real_world_data_path: ../data/2017-05-12_6C-50per_3_6C_CH36.csv
RESULTS_DIR: ./results/{time_stamp}
SIM_VS_SIM:
  baseline_sim_config: ../../generate_simulated_data/output/simulated_data_setting_SEI.yaml
  baseline_sim_id: 0
  parameter_change:
    SEI reaction exchange current density [A.m-2]: 3.0e-07
