EXPERIMENT_TYPE: real_vs_sim
EXP_CYCLES: 2
RANDOM_SEED: 1234
REAL_VS_SIM:
  real_world_cell_dataset: MATR
  real_world_data_path: ../data/2017-05-12_6C-50per_3_6C_CH36.csv
RESULTS_DIR: ./results/{time_stamp}
SIM_VS_SIM:
  baseline_sim_config: ../../generate_simulated_data/output/simulated_data_setting_multi_new_filtered.yaml
  baseline_sim_id: 4
  parameter_change:
    Negative electrode Bruggeman coefficient (electrolyte): 1.5
    Negative electrode porosity: 0.31
    Negative electrode thickness [m]: 9.372e-05
    Negative particle radius [m]: 5.86e-06
    Positive electrode Bruggeman coefficient (electrolyte): 1.5
    Positive electrode porosity: 0.395
    Positive electrode thickness [m]: 8.316e-05
    Positive particle radius [m]: 5.22e-06
    Separator thickness [m]: 1.2e-05
