initial_params = {
    "Nominal cell capacity [A.h]": 1.1,
    # geometry ----------------------------------------------------
    "Electrode width [m]": 0.0368,
    "Negative electrode thickness [m]": 6.70e-05,
    "Positive electrode thickness [m]": 8.70e-05,
    # micro-structure --------------------------------------------
    "Negative electrode active material volume fraction": 0.58,
    "Positive electrode active material volume fraction": 0.61,
    # stoichiometric limits --------------------------------------
    "Maximum concentration in negative electrode [mol.m-3]": 18500.0,
    "Maximum concentration in positive electrode [mol.m-3]": 48000.0,
    # initial lithium fractions ----------------------------------
    "Initial concentration in negative electrode [mol.m-3]": 17800.0,
    "Initial concentration in positive electrode [mol.m-3]": 21000.0,
}

params_to_update = {
    "Initial SEI thickness [m]": 4.5e-9,
    "Initial SEI on cracks thickness [m]": 5e-13,
    "SEI partial molar volume [m3.mol-1]": 1.3e-4,
    "SEI resistivity [Ohm.m]": 1.5e6,
    "SEI solvent diffusivity [m2.s-1]": 8e-21,
    "Bulk solvent concentration [mol.m-3]": 2636.0,
    "SEI reaction exchange current density [A.m-2]": 1e-11,
    "SEI open-circuit potential [V]": 0.4,
    "SEI electron conductivity [S.m-1]": 8.95e-14,
    "SEI lithium interstitial diffusivity [m2.s-1]": 1e-20,
    "Lithium interstitial reference concentration [mol.m-3]": 15.0,
    "EC initial concentration in electrolyte [mol.m-3]": 4541.0,
    "EC diffusivity [m2.s-1]": 2e-18,
    "SEI kinetic rate constant [m.s-1]": 1e-11,
    "SEI growth activation energy [J.mol-1]": 0.0,
    "Ratio of lithium moles to SEI moles": 5.0
}

initial_params_for_first_cycle = {
    "Nominal cell capacity [A.h]": 1.1,
    'Electrode width [m]': 0.04,
    'Negative electrode active material volume fraction': 0.61,
    'Positive electrode active material volume fraction': 0.62,
    'Negative electrode thickness [m]': 7.65e-05,
    'Positive electrode thickness [m]': 6.8e-05,
    'Maximum concentration in negative electrode [mol.m-3]': 28700.0,
    'Maximum concentration in positive electrode [mol.m-3]': 49943.0,
    'Initial concentration in negative electrode [mol.m-3]': 24108.0,
    'Initial concentration in positive electrode [mol.m-3]': 21725.0,
    'Negative electrode Bruggeman coefficient (electrode)': 0.0,
    'Positive electrode Bruggeman coefficient (electrode)': 0.0,
    'Negative electrode Bruggeman coefficient (electrolyte)': 2.914,
    'Positive electrode Bruggeman coefficient (electrolyte)': 1.83,
    'Separator Bruggeman coefficient (electrolyte)': 1.5,
    'Separator porosity': 0.5,
    'Separator thickness [m]': 2.5e-05,
    'Negative electrode charge transfer coefficient': 0.5,
    'Positive electrode charge transfer coefficient': 0.5,
    'Negative electrode conductivity [S.m-1]': 100.0,
    'Positive electrode conductivity [S.m-1]': 10.0,
    'Negative electrode double-layer capacity [F.m-2]': 0.2,
    'Positive electrode double-layer capacity [F.m-2]': 0.2,
    'Negative electrode porosity': 0.33,
    'Positive electrode porosity': 0.32,
    'Negative particle radius [m]': 5e-06,
    'Positive particle radius [m]': 3e-06
}
# initial_params_for_first_cycle = {
#     "Electrode width [m]": (0.01, 2.0),
#     "Negative electrode active material volume fraction": (0.3, 0.9),
#     "Positive electrode active material volume fraction": (0.26, 0.5),
#     "Negative electrode thickness [m]": (2e-05, 0.0001),
#     "Positive electrode thickness [m]": (5e-05, 0.00011),
#     "Maximum concentration in negative electrode [mol.m-3]": (23000, 35000),
#     "Maximum concentration in positive electrode [mol.m-3]": (18000, 30000),
#     "Initial concentration in negative electrode [mol.m-3]": (20000, 30000),
#     "Initial concentration in positive electrode [mol.m-3]": (0, 120.0),
#     "Negative electrode Bruggeman coefficient (electrode)": (1, 5),
#     "Positive electrode Bruggeman coefficient (electrode)": (1, 5),
#     "Negative electrode Bruggeman coefficient (electrolyte)": (1, 5),
#     "Positive electrode Bruggeman coefficient (electrolyte)": (1, 5),
#     "Separator Bruggeman coefficient (electrolyte)": (1, 5),
#     "Separator porosity": (0.3, 1.3),
#     "Separator thickness [m]": (6.000000000000001e-06, 3e-05),
#     "Negative electrode charge transfer coefficient": (0.2, 0.8),
#     "Positive electrode charge transfer coefficient": (0.2, 0.8),
#     "Negative electrode OCP entropic change [V.K-1]": (0, 1.0),
#     "Positive electrode OCP entropic change [V.K-1]": (0, 1.2),
#     "Negative electrode conductivity [S.m-1]": (10, 220),
#     "Positive electrode conductivity [S.m-1]": (0.1, 110),
#     "Negative electrode double-layer capacity [F.m-2]": (0.1, 0.3),
#     "Positive electrode double-layer capacity [F.m-2]": (0.1, 0.3),
#     "Negative electrode porosity": (0.2, 0.5),
#     "Positive electrode porosity": (0.14, 0.5),
#     "Negative particle diffusivity [m2.s-1]": (3e-15, 3.3e-14),
#     "Positive particle diffusivity [m2.s-1]": (5.9e-18, 1e-14),
#     "Negative particle radius [m]": (5.08e-07, 1.37e-05),
#     "Positive particle radius [m]": (1e-16, 1.37e-05),
# }
